### PR TITLE
updated CppMappingRulesExtensions

### PR DESCRIPTION
**Pull request by StephenHodgson**
- added DllImportLibrary
- updated DefaultDllImportConverter

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Ah, checks failing bc we need that `CppElement.SourceFile` change we made in https://github.com/xoofx/CppAst/pull/30

**Comment by xoofx** [comment]
> Ah, checks failing bc we need that `CppElement.SourceFile` change we made in [xoofx/CppAst#30](https://github.com/xoofx/CppAst/pull/30)

Do you have more changes coming to CppAst? If yes, continue working with a local copy, open PRs to CppAst, once you are confident/done with the changes, I will release a new version of CppAst and you will be able to proceed with the remaining PR here.

**Comment by StephenHodgson** [comment]
I don't believe I do, but give me a day or two to sort through it to make sure I don't.

**Comment by StephenHodgson** [comment]
Okay I _think_ that's everything for CppAst.

https://github.com/xoofx/CppAst/pull/32

**Pull request merged**
